# Generated by Django 4.2.11 on 2024-04-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='number_of_rows',
            field=models.IntegerField(default=0),
        ),
    ]
