# Generated by Django 4.2.11 on 2024-04-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0002_file_number_of_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFile',
            fields=[
                ('file_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField()),
                ('size', models.FloatField()),
                ('number_of_rows', models.IntegerField(default=0)),
            ],
        ),
    ]
