# Generated by Django 4.2.11 on 2024-04-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0003_processingfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='last_modified',
            new_name='parent_zip_last_modified',
        ),
        migrations.RenameField(
            model_name='processingfile',
            old_name='last_modified',
            new_name='parent_zip_last_modified',
        ),
    ]
