# Generated by Django 4.2.11 on 2024-04-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0004_rename_last_modified_file_parent_zip_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='processingfile',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
