# Generated by Django 4.2.11 on 2024-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0005_alter_file_size_alter_processingfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.AutoField(default=345, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingfile',
            name='file_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='processingfile',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
