# Generated by Django 4.2.11 on 2024-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0006_file_file_id_processingfile_file_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ProcessedFile',
        ),
    ]
