# Generated by Django 4.2.11 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0007_rename_file_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
