# Generated by Django 4.2.11 on 2024-04-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityBikeApp', '0009_alter_station_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='bike_id',
            new_name='bike',
        ),
    ]
